packages:
  - ./apps/*
  - ./packages/*

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@scarf/scarf'
  - '@tailwindcss/oxide'

injectWorkspacePackages: true

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild

syncInjectedDepsAfterScripts:
  - build
