packages:
  - ./apps/*

ignoredBuiltDependencies:
  - '@scarf/scarf'
  - '@tailwindcss/oxide'

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@swc/core'
  - better-sqlite3
  - esbuild

syncInjectedDepsAfterScripts:
  - build
