# ./apps/frontend/Dockerfile.dev
FROM base

# Development setup needs the full source code
WORKDIR /app

# Set working directory to app folder
WORKDIR /app/apps/frontend

# Set development environment
ENV NODE_ENV=development

# Start in development mode
CMD ["pnpm", "dev"]